Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingCart.Infrastructure;
using ShoppingCart.Models;

namespace ShoppingCart.Controllers
{
        public class ProductsController : Controller
        {
                private readonly DataContext _context;

                public ProductsController(DataContext context)
                {
                        _context = context;
                }

                public async Task<IActionResult> Index(string categorySlug = "", int p = 1)
                {
                        int pageSize = 8;
                        ViewBag.PageNumber = p;
                        ViewBag.PageRange = pageSize;
                        ViewBag.CategorySlug = categorySlug;

                        if (categorySlug == "")
                        {
                                ViewBag.TotalPages = (int)Math.Ceiling((decimal)_context.Products.Count() / pageSize);

                                return View(await _context.Products.OrderByDescending(p => p.Id).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync());
                        }

                        Category category = await _context.Categories.Where(c => c.Slug == categorySlug).FirstOrDefaultAsync();
                        if (category == null) return RedirectToAction("Index");

                        var productsByCategory = _context.Products.Where(p => p.CategoryId == category.Id);
                        ViewBag.TotalPages = (int)Math.Ceiling((decimal)productsByCategory.Count() / pageSize);

                        return View(await productsByCategory.OrderByDescending(p => p.Id).Skip((p - 1) * pageSize).Take(pageSize).ToListAsync());
                }
         
        
        
        //[HttpGet] 
        //public async Task<IActionResult>  SearchBar(string ProductName)
        //{
        //    ViewData["GetProductDetails"] = ProductName;
        //    var projectquery = from x in _context.Products select x;
        //    if(!String.IsNullOrEmpty(ProductName))
        //    {
        //        projectquery=projectquery.Where(x=>x.Name.Contains(ProductName));
        //    }
        //    return View(await projectquery.AsNoTracking().ToListAsync());
        //}



    }
}

Controllers/StripeDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Data.ViewModels;
using Stripe;

namespace ShoppingCart.Controllers
{
    public class StripeDashboardController : Controller
    {
        public IActionResult StripeIndex()
        {
            var response = new StripeDashboardVM();

            var balanceService = new BalanceService();
            var balanceResult = balanceService.Get();
            response.Balance = balanceResult;

            var transactionService = new BalanceTransactionService();
            var transactionsResult = transactionService.List().ToList();
            response.Transactions = transactionsResult;

            var customerService = new CustomerService();
            var customerResult = customerService.List().ToList();
            response.Customers = customerResult;

            var chargeService = new ChargeService();
            var chargeResult = chargeService.List().ToList();
            response.Charges = chargeResult;

            var disputeService = new DisputeService();
            var disputeResult = disputeService.List().ToList();
            response.Disputes = disputeResult;

            var refundService = new RefundService();
            var refundResult = refundService.List().ToList();
            response.Refunds = refundResult;

            var productService = new ProductService();
            var productResult = productService.List().ToList();
            response.Products = productResult;

            return View(response);
        }
    }
}
 

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
<title>Easy Admin Panel an Admin Panel Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Easy Admin Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="~/adminStyles/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="~/adminStyles/css/style.css" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="~/adminStyles/css/font-awesome.css" rel="stylesheet"> 
<!-- jQuery -->
<!-- lined-icons -->
<link rel="stylesheet" href="~/adminStyles/css/icon-font.min.css" type='text/css' />
<!-- //lined-icons -->
<!-- chart -->
<script src="~/adminStyles/js/Chart.js"></script>
<!-- //chart -->
<!--animate-->
<link href="~/adminStyles/css/animate.css" rel="stylesheet" type="text/css" media="all">
<script src="~/adminStyles/js/wow.min.js"></script>
    <script>
         new WOW().init();
    </script>
<!--//end-animate-->
<!----webfonts--->
<link href='//fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<!---//webfonts---> 
 <!-- Meters graphs -->
<script src="~/adminStyles/js/jquery-1.10.2.min.js"></script>
<!-- Placed js at the end of the document so the pages load faster -->

</head>
<body class="sticky-header left-side-collapsed"  onload="initMap()">
	<section>
	<!-- left side start-->
		<div class="left-side sticky-left-side">

			<!--logo and iconic logo start-->
			<div class="logo">
				<h1><a href="index.html">Easy <span>Admin</span></a></h1>
			</div>
			<div class="logo-icon text-center">
				@*<a href="index.html"><i class="lnr lnr-home"></i> </a>*@
				<a asp-controller="Home" asp-action="Index" asp-area="Home"><i class="lnr lnr-home"></i> </a>
			</div>

			<!--logo and iconic logo end-->
			<div class="left-side-inner">

				<!--sidebar nav start-->
					<ul class="nav nav-pills nav-stacked custom-nav">
						<li class="active"><a href="index.html"><i class="lnr lnr-power-switch"></i><span>Dashboard</span></a></li>
						
						<li><a asp-controller="Products" asp-action="Index" asp-area="Admin"><i class="lnr lnr-spell-check"></i> <span>Products</span></a></li>
				<li><a asp-controller="StripeDashboard" asp-action="StripeIndex" asp-area="Home"><i class="lnr lnr-spell-check"></i> <span>Stripe</span></a></li>
						
						
						
					</ul>
				<!--sidebar nav end-->
			</div>
		</div>
		</section>


    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col">
                    <partial name="_NotificationPartial" />
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>


	 <!--footer section start-->
			<footer>
		<p>© 2017 Prezzie_admin_panel. All rights reserved </a></p>
			</footer>
		<!--footer section end-->

	  <!-- main content end-->
   </section>

<script src="~/adminStyles/js/jquery.nicescroll.js"></script>
<script src="~/adminStyles/js/scripts.js"></script>
<!-- Bootstrap Core JavaScript -->
   <script src="~/adminStyles/js/bootstrap.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
        <div class="alert alert-success notification">
                @TempData["Success"]
        </div>
}