Models/ViewModels/CartViewModel.cs
namespace ShoppingCart.Models.ViewModels
{
        public class CartViewModel
        {
                public List<CartItem> CartItems { get; set; }
                public decimal GrandTotal { get; set; }
        }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Infrastructure;
using ShoppingCart.Models;
using ShoppingCart.Models.ViewModels;

namespace ShoppingCart.Controllers
{
        public class CartController : Controller
        {
                private readonly DataContext _context;

                public CartController(DataContext context)
                {
                        _context = context;
                }

                public IActionResult Index()
                {
                        List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart") ?? new List<CartItem>();

            CartViewModel cartVM = new()
            {
                CartItems = cart,
                GrandTotal = Math.Round(cart.Sum(x => x.Quantity * x.Price), 2)
                        };
            
            return View(cartVM);
                }

                public async Task<IActionResult> Add(long id)
                {
                        Product product = await _context.Products.FindAsync(id);

                        List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart") ?? new List<CartItem>();

                        CartItem cartItem = cart.Where(c => c.ProductId == id).FirstOrDefault();

                        if (cartItem == null)
                        {
                                cart.Add(new CartItem(product));
                        }
                        else
                        {
                                cartItem.Quantity += 1;
                        }

                        HttpContext.Session.SetJson("Cart", cart);

                        TempData["Success"] = "The product has been added!";

                        return Redirect(Request.Headers["Referer"].ToString());
                }

                public async Task<IActionResult> Decrease(long id)
                {
                        List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");

                        CartItem cartItem = cart.Where(c => c.ProductId == id).FirstOrDefault();

                        if (cartItem.Quantity > 1)
                        {
                                --cartItem.Quantity;
                        }
                        else
                        {
                                cart.RemoveAll(p => p.ProductId == id);
                        }

                        if (cart.Count == 0)
                        {
                                HttpContext.Session.Remove("Cart");
                        }
                        else
                        {
                                HttpContext.Session.SetJson("Cart", cart);
                        }

                        TempData["Success"] = "The product has been removed!";

                        return RedirectToAction("Index");
                }

                public async Task<IActionResult> Remove(long id)
                {
                        List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");

                        cart.RemoveAll(p => p.ProductId == id);

                        if (cart.Count == 0)
                        {
                                HttpContext.Session.Remove("Cart");
                        }
                        else
                        {
                                HttpContext.Session.SetJson("Cart", cart);
                        }

                        TempData["Success"] = "The product has been removed!";

                        return RedirectToAction("Index");
                }

                public IActionResult Clear()
                {
                        HttpContext.Session.Remove("Cart");

                        return RedirectToAction("Index");
                }
        }
}

Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Helpers;
using Stripe;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;
using ShoppingCart.Infrastructure;
using ShoppingCart.Models.ViewModels;

namespace ShoppingCart.Controllers
{
    public class CheckoutController : Controller
    {

      [TempData]
        public string TotalAmount { get; set; }
        public IActionResult Index()
        {
           // var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
          /*  ViewBag.cart = cart;
            ViewBag.DollarAmount = cart.Sum(x => x.Quantity * x.Price);
            ViewBag.total = Math.Round(ViewBag.DollarAmount, 2) * 100;
            ViewBag.total = Convert.ToInt64(ViewBag.total);
            long total = ViewBag.total;
            TotalAmount = total.ToString();
            return View();*/

           List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart") ?? new List<CartItem>();

            CartViewModel cartVM = new()
            {
                CartItems = cart,
                GrandTotal = Convert.ToInt64(Math.Round(cart.Sum(x => x.Quantity * x.Price), 2) * 100)
             };
           // long total = cartVM.GrandTotal;
           TotalAmount = cartVM.GrandTotal.ToString();
            return View(cartVM);
        }
        [HttpPost]
        public IActionResult Processing(string stripeToken, string stripeEmail)
        {
            var optionsCust = new CustomerCreateOptions
            {
                Email = stripeEmail,
                Name = "Rizwana",
                Phone = "04-234567"

            };
            var serviceCust = new CustomerService();
            Customer customer = serviceCust.Create(optionsCust);
            var optionsCharge = new ChargeCreateOptions
            {
                /*Amount = HttpContext.Session.GetLong("Amount")*/
                Amount = Convert.ToInt64(TempData["TotalAmount"]),
                Currency = "CAD",
                Description = "Buying Cakes",
                Source = stripeToken,
                ReceiptEmail = stripeEmail,

            };
            var service = new ChargeService();
            Charge charge = service.Create(optionsCharge);
            if (charge.Status == "succeeded")
            {
                string BalanceTransactionId = charge.BalanceTransactionId;
                ViewBag.AmountPaid = Convert.ToDecimal(charge.Amount) % 100 / 100 + (charge.Amount) / 100;
                ViewBag.BalanceTxId = BalanceTransactionId;
                ViewBag.Customer = customer.Name;
                //return View();
            }

           

            return View();
        }
    }
       
}

Views/Cart/Index.cshtml
@model CartViewModel

@{
        ViewData["Title"] = "Cart Overview";
}
<br />
<br />
 <div class="container" >
@if (Model.CartItems.Count > 0)


{

        
        <table class="table">
                <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th></th>
                        <th>Price</th>
                        <th>Total</th>
                </tr>
                @foreach (var item in Model.CartItems)
                {
                        <tr>
                                <td>@item.ProductName</td>
                                <td>@item.Quantity</td>
                                <td>
                                        <a class="btn btn-primary btn-sm" asp-action="Add" asp-route-id="@item.ProductId">+</a>
                                        <a class="btn btn-info btn-sm" asp-action="Decrease" asp-route-id="@item.ProductId">-</a>
                                        <a class="btn btn-danger btn-sm" asp-action="Remove" asp-route-id="@item.ProductId">Remove</a>
                                </td>
                                <td>@item.Price.ToString("C2")</td>
                                <td>@Model.CartItems.Where(x => x.ProductId == item.ProductId).Sum(x => x.Quantity * x.Price).ToString("C2")</td>
                        </tr>
                }
                <tr>
                        <td class="text-right" colspan="4">Grand Total: @Model.GrandTotal.ToString("C2")</td>
               @* <td class="text-right" colspan="4">Grand Total: @Math.Round(@Model.GrandTotal/100,2,MidpointRounding.AwayFromZero).ToString("F2")</td>*@
                </tr>
                <tr>
                        <td class="text-right" colspan="4">
                    <a class="btn btn-lg btn-danger" asp-action="Clear">Clear Cart</a>
                                
                <a class="btn btn-lg btn-primary" asp-controller="Checkout" asp-action="Index">Checkout</a>
                        </td>

                </tr>
        </table>
   

    



}
else
{ 
    <div class="text-center">
        <div class="d-flex w-100 justify-content-center">
        <h3 class="display-4 text-center">Your cart is empty.</h3>
        </div>
        </div>
}
</div>